backend:
  name: github
  repo: RogerTerrazas/HernandezHauling
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "General"
        name: "general"
        file: "src/content/general.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Address, name: address, widget: string}
          - {label: Phone, name: phone, widget: string}
          - {label: Facebook, name: facebook, widget: string, default: "", required: false}
          - {label: Instagram, name: instagram, widget: string, default: "", required: false}

      - label: "Home Page"
        name: "home"
        file: "src/content/home.yml"
        fields:
          - label: Home Content
            name: HomeContent
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}
          - label: "Service Cards"
            name: serviceCard
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}

          - label: "Services"
            name: services
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
        
      - label: "About Page"
        name: "about"
        file: "src/content/about.yml"
        fields:
          - label: About Content
            name: AboutContent
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}
          - label: "Tesitimonials"
            name: Tesitimonials
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Date, name: date, widget: string}
              - {label: Content, name: content, widget: string}
          

